// G:\quake2\baseq2\models/monsters/berserk

// This file generated by ModelGen - Do NOT Modify

#define FRAME_walk01          	0
#define FRAME_walk02          	1
#define FRAME_walk03        	2
#define FRAME_walk04         	3
#define FRAME_walk05         	4
#define FRAME_walk06        	5
#define FRAME_walk07        	6
#define FRAME_walk08         	7
#define FRAME_walk09			8
#define FRAME_walk10			9
#define FRAME_walk12			10
#define FRAME_stand01			11
#define FRAME_stand02			12
#define FRAME_stand03			13
#define FRAME_stand04			14
#define FRAME_stand05			15
#define FRAME_stand06			16
#define FRAME_stand07			17
#define FRAME_stand08			18
#define FRAME_stand09			19
#define FRAME_stand10			20
#define FRAME_stand11			21
#define FRAME_stand12			22
#define FRAME_stand13			23
#define FRAME_stand14			24
#define FRAME_stand15			25
#define FRAME_stand16			26
#define FRAME_stand17			27
#define FRAME_stand18			28
#define FRAME_stand19			29
#define FRAME_stand20			30
#define FRAME_pain01			31
#define FRAME_pain02			32
#define FRAME_pain03			33
#define FRAME_pain04			34
#define FRAME_pain05			35
#define FRAME_pain06			36
#define FRAME_pain07			37
#define FRAME_pain08			38
#define FRAME_pain09			39
#define FRAME_pain10			40
#define FRAME_pain11			41

#define MODEL_SCALE		1.000000
