#!/bin/sh

EXCUSE="\
Nexuiz client wrapper\n\
This script is Debian specific, it is *NOT* part of the source distribution!\n\
Usage: alienarena2007-server [OPTION]...\n\
\n\
 -h, --help\t\tDisplay this help\n\
 -q, --quiet\t\tDisable console output\n\
 -s, --service\t\tLaunch server as a service\n\
 -k, --kill\t\tKill a runaway server session\n\
 -Q, --query\t\tQuery local servers\n\
 -r, --rcon\t\tSends rcon commands to servers\n\
 +<internal command>\tPass commands to the engine\n"

QUIET=0
LAUNCH_SERVER_AS_SERVICE=0
KILL_RUNAWAY_CRDED=0
SVSTAT=0
RCON=0

case "$1" in
	-h|--help)
		echo -e ${EXCUSE}
		exit 0
		;;
	-q|--quiet)
		QUIET=1
		shift
		;;
	-s|--service)
		LAUNCH_SERVER_AS_SERVICE=1
		shift
		;;
	-k|--kill)
		KILL_RUNAWAY_CRDED=1
		shift
		;;
	-Q|--query)
		SVSTAT=1
		shift
		;;
	-r|--rcon)
		RCON=1
		shift
		;;
esac

# Ready to rumble!
cd /usr/share/games/alienarena2007

if [ ${LAUNCH_SERVER_AS_SERVICE} = 1 ]; then
	exec /usr/lib/games/alienarena2007/launch-server "$@"
elif [ ${KILL_RUNAWAY_CRDED} = 1 ]; then
	exec /usr/lib/games/alienarena2007/kill-runaway-crded "$@"
elif [ ${SVSTAT} = 1 ]; then
	exec /usr/lib/games/alienarena2007/svstat "$@"
elif [ ${RCON} = 1 ]; then
	exec /usr/lib/games/alienarena2007/rcon "$@"
elif [ ${QUIET} = 1 ]; then
	exec /usr/lib/games/alienarena2007/crded "$@" >/dev/null 2>&1
else
	exec /usr/lib/games/alienarena2007/crded "$@"
fi
