#!/bin/sh

USAGE="\
Alien Arena 2007 client wrapper\n\
This script is Debian specific, it is *NOT* part of the source distribution!\n\
Usage: alienarena2007 [OPTION] [PARAMETERS]...\n\
\n\
 -h, --help\t\tDisplay this help\n\
 -q, --quiet\t\tDisable console output\n\
 [PARAMETERS]\tPass internal parameters to the client\n"

QUIET=0

case "$1" in
	-h|--help)
		echo -e ${USAGE}
		exit 0
		;;
	-q|--quiet)
		QUIET=1
		shift
		;;
esac

# Ready to rumble!
cd /usr/share/games/alienarena2007

if [ ${QUIET} = 1 ]; then
	exec /usr/lib/games/alienarena2007/crx.sdl "$@" >/dev/null 2>&1
else
	exec /usr/lib/games/alienarena2007/crx.sdl "$@"
fi
