// G:\quake2\baseq2\models/monsters/berserk

// This file generated by ModelGen - Do NOT Modify

#define FRAME_walk01          	0
#define FRAME_walk02          	1
#define FRAME_walk03        	2
#define FRAME_walk04         	3
#define FRAME_walk05         	4
#define FRAME_walk06        	5
#define FRAME_walk07        	6
#define FRAME_walk08         	7
#define FRAME_walk09			8
#define FRAME_walk10			9
#define FRAME_walk11			10
#define FRAME_walk12			11
#define FRAME_stand01			12
#define FRAME_stand02			13
#define FRAME_stand03			14
#define FRAME_stand04			15
#define FRAME_stand05			16
#define FRAME_stand06			17
#define FRAME_stand07			18
#define FRAME_stand08			19
#define FRAME_stand09			20
#define FRAME_stand10			21
#define FRAME_stand11			22
#define FRAME_stand12			23
#define FRAME_stand13			24
#define FRAME_stand14			25
#define FRAME_stand15			26
#define FRAME_stand16			27
#define FRAME_stand17			28
#define FRAME_stand18			29
#define FRAME_stand19			30
#define FRAME_stand20			31
#define FRAME_pain01			32
#define FRAME_pain02			33
#define FRAME_pain03			34
#define FRAME_pain04			35
#define FRAME_pain05			36
#define FRAME_pain06			37
#define FRAME_pain07			38
#define FRAME_pain08			39
#define FRAME_pain09			40
#define FRAME_pain10			41
#define FRAME_pain11			42

#define MODEL_SCALE		1.000000
