#! /bin/sh -e
if [ `dpkg -s alienarena2007-server |grep Status |cut -d' ' -f4` = "installed" ]; then
	ln -sf /usr/lib/games/alienarena2007/server.so /usr/share/games/alienarena2007/arena/game.so
	ln -sf /usr/lib/games/alienarena2007/server.so /usr/share/games/alienarena2007/data1/game.so
else
	rm -f /usr/share/games/alienarena2007/arena/game.so
	rm -f /usr/share/games/alienarena2007/data1/game.so
fi
