#! /bin/sh -e
#DEBHELPER#
if [ `dpkg -s alienarena2007-server |grep Status |cut -d' ' -f4` = "installed" ]; then
	ln -sf /usr/lib/games/alienarena2007/server.so /usr/share/games/alienarena2007/arena/game.so
	ln -sf /usr/lib/games/alienarena2007/server.so /usr/share/games/alienarena2007/data1/game.so
elif test -e /usr/games/alienarena2007; then
	exit 0 # Exit if alienarena2007 is still installed
else
	rm -f /usr/share/games/alienarena2007/arena/game.so
	rm -f /usr/share/games/alienarena2007/data1/game.so
	rm -rf $HOME/.alienarena2007
fi
