#! /bin/sh -e
if test -e /usr/games/alienarena2007-server; then
	exit 0 # Exit if alienarena2007-server is still installed
elif [ `dpkg -s alienarena2007 |grep Status |cut -d' ' -f4` = "installed" ]; then
	exit 0 # Exit if alienarena2007 is still installed
else
	rm -f /usr/share/games/alienarena2007/arena/game.so
	rm -f /usr/share/games/alienarena2007/data1/game.so
	rm -rf $HOME/.alienarena2007
fi
